# File: .gitlab-ci.yml
# CI/CD pipeline configuration for the Notes App

# Define pipeline stages
stages:
  - build
  - test
  - security
  - package
  - deploy

# Global variables
variables:
  APP_NAME: "notes-app"
  APP_VERSION: "1.0.0"
  NODE_ENV: "production"

############################################
# STAGE 1: BUILD
############################################
build-job:
  stage: build
  image: node:18
  script: 
    - echo "Installing dependencies..."
    - npm install
    - echo "Checking syntax of server files..."
    - node -c app.js
    - node -c tasks.js
    - echo "Build completed successfully!"
  artifacts: 
    # Save node_modules for the next stages
    paths:
      - node_modules/
    expire_in: 1 hour

############################################
# STAGE 2: TEST
############################################
test-job: 
  stage: test
  image: node:18
  script:
    - echo "Running unit tests..."
    - npm test
    - echo "All tests passed!"
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

############################################
# STAGE 3: SECURITY
############################################
security-secrets-scan:
  stage: security
  image: zricethezav/gitleaks:latest
  script:
    - echo "Scanning code for secrets..."
    - gitleaks detect --source=. --verbose --no-git
    - echo "No secrets found!"
  allow_failure: false

security-dependencies-scan:
  stage: security
  image: node:18
  script:
    - echo "Checking dependencies for vulnerabilities..."
    - npm audit --audit-level=high
    - echo "No critical vulnerabilities found!"
  allow_failure: false

############################################
# STAGE 4: PACKAGE
############################################
package-docker:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t $APP_NAME:$APP_VERSION .
    - docker build -t $APP_NAME:latest .
    - echo "Docker image built successfully!"
    - docker images
  only:
    - main

############################################
# STAGE 5: DEPLOY
############################################
deploy-staging:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying to staging..."
    - docker stop notes-app-staging || true
    - docker rm notes-app-staging || true
    - docker run -d --name notes-app-staging -p 3000:3000 $APP_NAME:$APP_VERSION
    - echo "Notes app deployed on staging!"
  environment:
    name: staging
    url: http://staging.notes-app.local:3000
  only:
    - main

deploy-production:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Deploying to PRODUCTION..."
    - docker stop notes-app-prod || true
    - docker rm notes-app-prod || true
    - docker run -d --name notes-app-prod -p 8080:3000 $APP_NAME:$APP_VERSION
    - echo "Notes app deployed to PRODUCTION!"
  environment:
    name: production
    url: http://www.notes-app.com
  when: manual
  only:
    - main

